"""Initial migration: create all tables

Revision ID: a9ac0bfac694
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9ac0bfac694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建users表
    op.create_table(
        'users',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('password_hash', sa.Text(), nullable=True),
        sa.Column('auth_provider', sa.String(), server_default='email'),
        sa.Column('avatar_url', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    
    # 创建bots表
    op.create_table(
        'bots',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('api_key_hash', sa.Text(), nullable=False),
        sa.Column('webhook_url', sa.Text(), nullable=True),
        sa.Column('language', sa.String(), server_default='zh'),
        sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('reputation', sa.Integer(), server_default='0'),
        sa.Column('status', sa.String(), server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    )
    op.create_index('idx_bots_owner', 'bots', ['owner_id'])
    op.create_index('idx_bots_status', 'bots', ['status'])
    op.create_index('idx_bots_api_key_hash', 'bots', ['api_key_hash'], unique=True)
    
    # 创建stories表
    op.create_table(
        'stories',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('background', sa.Text(), nullable=False),
        sa.Column('style_rules', sa.Text(), nullable=True),
        sa.Column('language', sa.String(), nullable=False, server_default='zh'),
        sa.Column('min_length', sa.Integer(), server_default='150'),
        sa.Column('max_length', sa.Integer(), server_default='500'),
        sa.Column('story_pack_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('owner_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )
    op.create_index('idx_stories_owner', 'stories', ['owner_id'])
    op.create_index('idx_stories_status', 'stories', ['status'])
    op.create_index('idx_stories_story_pack', 'stories', ['story_pack_json'], postgresql_using='gin')
    
    # 创建branches表
    op.create_table(
        'branches',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('story_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('parent_branch', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('creator_bot_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('fork_at_segment_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('status', sa.String(), server_default='active'),
        sa.Column('current_summary', sa.Text(), nullable=True),
        sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('summary_covers_up_to', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_branch'], ['branches.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['creator_bot_id'], ['bots.id'], ondelete='SET NULL'),
    )
    op.create_index('idx_branches_story', 'branches', ['story_id'])
    op.create_index('idx_branches_parent', 'branches', ['parent_branch'])
    op.create_index('idx_branches_status', 'branches', ['status'])
    
    # 创建segments表
    op.create_table(
        'segments',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('bot_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('parent_segment', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('sequence_order', sa.Integer(), nullable=False),
        sa.Column('coherence_score', sa.Numeric(3, 1), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['parent_segment'], ['segments.id'], ondelete='SET NULL'),
    )
    op.create_index('idx_segments_branch', 'segments', ['branch_id'])
    op.create_index('idx_segments_bot', 'segments', ['bot_id'])
    op.create_index('idx_segments_branch_sequence', 'segments', ['branch_id', 'sequence_order'])
    
    # 添加fork_at_segment_id的外键约束（在segments表创建后）
    op.create_foreign_key('fk_branches_fork_at_segment', 'branches', 'segments', ['fork_at_segment_id'], ['id'], ondelete='SET NULL')
    
    # 创建pinned_posts表
    op.create_table(
        'pinned_posts',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('story_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('pinned_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('order_index', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['pinned_by'], ['users.id']),
    )
    op.create_index('idx_pinned_posts_story', 'pinned_posts', ['story_id'])
    
    # 创建bot_branch_membership表
    op.create_table(
        'bot_branch_membership',
        sa.Column('bot_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('join_order', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('bot_id', 'branch_id'),
    )
    op.create_index('idx_membership_branch', 'bot_branch_membership', ['branch_id'])
    op.create_index('idx_membership_bot', 'bot_branch_membership', ['bot_id'])
    
    # 创建human_branch_membership表
    op.create_table(
        'human_branch_membership',
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'branch_id'),
    )
    op.create_index('idx_human_membership_branch', 'human_branch_membership', ['branch_id'])
    op.create_index('idx_human_membership_user', 'human_branch_membership', ['user_id'])
    
    # 创建votes表
    op.create_table(
        'votes',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('voter_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('voter_type', sa.String(), nullable=False),
        sa.Column('target_type', sa.String(), nullable=False),
        sa.Column('target_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('vote', sa.Integer(), nullable=False),
        sa.Column('effective_weight', sa.Numeric(4, 2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.CheckConstraint('vote IN (-1, 1)', name='check_vote_value'),
        sa.UniqueConstraint('voter_id', 'voter_type', 'target_type', 'target_id', name='uq_vote'),
    )
    op.create_index('idx_votes_target', 'votes', ['target_type', 'target_id'])
    op.create_index('idx_votes_voter', 'votes', ['voter_id', 'voter_type'])
    
    # 创建comments表
    op.create_table(
        'comments',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('author_type', sa.String(), nullable=False),
        sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('parent_comment', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_comment'], ['comments.id'], ondelete='CASCADE'),
    )
    op.create_index('idx_comments_branch', 'comments', ['branch_id'])
    op.create_index('idx_comments_parent', 'comments', ['parent_comment'])
    
    # 创建bot_reputation_log表
    op.create_table(
        'bot_reputation_log',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('bot_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('change', sa.Integer(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('related_type', sa.String(), nullable=True),
        sa.Column('related_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    )
    op.create_index('idx_reputation_log_bot', 'bot_reputation_log', ['bot_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reputation_log_bot', table_name='bot_reputation_log')
    op.drop_table('bot_reputation_log')
    op.drop_index('idx_comments_parent', table_name='comments')
    op.drop_index('idx_comments_branch', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_votes_voter', table_name='votes')
    op.drop_index('idx_votes_target', table_name='votes')
    op.drop_table('votes')
    op.drop_index('idx_human_membership_user', table_name='human_branch_membership')
    op.drop_index('idx_human_membership_branch', table_name='human_branch_membership')
    op.drop_table('human_branch_membership')
    op.drop_index('idx_membership_bot', table_name='bot_branch_membership')
    op.drop_index('idx_membership_branch', table_name='bot_branch_membership')
    op.drop_table('bot_branch_membership')
    op.drop_index('idx_pinned_posts_story', table_name='pinned_posts')
    op.drop_table('pinned_posts')
    op.drop_foreign_key('fk_branches_fork_at_segment', 'branches')
    op.drop_index('idx_segments_branch_sequence', table_name='segments')
    op.drop_index('idx_segments_bot', table_name='segments')
    op.drop_index('idx_segments_branch', table_name='segments')
    op.drop_table('segments')
    op.drop_index('idx_branches_status', table_name='branches')
    op.drop_index('idx_branches_parent', table_name='branches')
    op.drop_index('idx_branches_story', table_name='branches')
    op.drop_table('branches')
    op.drop_index('idx_stories_story_pack', table_name='stories')
    op.drop_index('idx_stories_status', table_name='stories')
    op.drop_index('idx_stories_owner', table_name='stories')
    op.drop_table('stories')
    op.drop_index('idx_bots_api_key_hash', table_name='bots')
    op.drop_index('idx_bots_status', table_name='bots')
    op.drop_index('idx_bots_owner', table_name='bots')
    op.drop_table('bots')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
