#!/bin/bash
#===============================================================================
# InkPath Cron Setup Script
# Purpose: Configure cron jobs for scheduled story continuation and monitoring
# Usage: ./setup_cron.sh [--install] [--remove] [--list] [--test]
#===============================================================================

set -e

# Configuration
PROJECT_DIR="/Users/admin/Desktop/work/inkPath"
LOG_DIR="${PROJECT_DIR}/logs"
CRON_LOG="${LOG_DIR}/cron.log"
AGENT_RUN_LOG="${LOG_DIR}/agent_runs.log"
PID_DIR="${PROJECT_DIR}/.pids"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

#===============================================================================
# Helper Functions
#===============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

ensure_directories() {
    log_info "Creating necessary directories..."
    mkdir -p "${LOG_DIR}"
    mkdir -p "${PID_DIR}"
    mkdir -p "${PROJECT_DIR}/scripts"
    log_success "Directories created"
}

#===============================================================================
# Cron Job Definitions
#===============================================================================

define_cron_jobs() {
    # Crontab entries
    cat << EOF
# InkPath Cron Jobs
# Generated by setup_cron.sh on $(date '+%Y-%m-%d %H:%M:%S')

# Environment
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin:/Users/admin/Desktop/work/inkPath/venv/bin
PYTHONPATH=/Users/admin/Desktop/work/inkPath

#------------------------------------------------------------------------------
# Story Continuation Jobs
#------------------------------------------------------------------------------

# Run story continuation agent every 15 minutes
*/15 * * * * cd "${PROJECT_DIR}" && python -m src.services.story_continuation_agent >> "${AGENT_RUN_LOG}" 2>&1

# Run story continuation agent with detailed logging
0,30 * * * * cd "${PROJECT_DIR}" && /Users/admin/Desktop/work/inkPath/scripts/run_agent.sh >> "${AGENT_RUN_LOG}" 2>&1

#------------------------------------------------------------------------------
# Monitoring Jobs
#------------------------------------------------------------------------------

# Health check every minute (for Better Uptime heartbeat)
* * * * * cd "${PROJECT_DIR}" && python -c "import requests; requests.get('https://inkpath-api.onrender.com/api/v1/health', timeout=10)" 2>/dev/null || echo "Health check failed: \$(date)" >> "${CRON_LOG}"

# Log monitoring stats every hour
0 * * * * cd "${PROJECT_DIR}" && python -c "
import os
log_file = '${AGENT_RUN_LOG}'
if os.path.exists(log_file):
    lines = sum(1 for line in open(log_file))
    print(f'Agent runs log: {lines} lines')
" >> "${CRON_LOG}" 2>&1

#------------------------------------------------------------------------------
# Database Maintenance Jobs
#------------------------------------------------------------------------------

# Cleanup expired data daily at 3 AM
0 3 * * * cd "${PROJECT_DIR}" && python -m src.services.cron_service cleanup_expired_data >> "${CRON_LOG}" 2>&1

# Update activity scores every hour
0 * * * * cd "${PROJECT_DIR}" && python -m src.services.cron_service update_activity_scores >> "${CRON_LOG}" 2>&1

#------------------------------------------------------------------------------
# Bot Management Jobs
#------------------------------------------------------------------------------

# Check bot timeouts every 5 minutes
*/5 * * * * cd "${PROJECT_DIR}" && python -m src.services.cron_service check_bot_timeouts >> "${CRON_LOG}" 2>&1

#------------------------------------------------------------------------------
# Summary Generation Jobs
#------------------------------------------------------------------------------

# Generate summaries for active branches every hour
30 * * * * cd "${PROJECT_DIR}" && python -m src.services.summary_service auto_generate >> "${CRON_LOG}" 2>&1

#------------------------------------------------------------------------------
# Log Rotation (if logrotate not available)
#------------------------------------------------------------------------------

# Rotate agent runs log weekly on Sunday at midnight
0 0 * * 0 cd "${PROJECT_DIR}" && if [ -f "${AGENT_RUN_LOG}" ]; then mv "${AGENT_RUN_LOG}" "${AGENT_RUN_LOG}.backup"; touch "${AGENT_RUN_LOG}"; gzip "${AGENT_RUN_LOG}.backup" 2>/dev/null || true; fi >> "${CRON_LOG}" 2>&1

EOF
}

#===============================================================================
# Main Functions
#===============================================================================

install_cron() {
    log_info "Installing InkPath cron jobs..."
    
    ensure_directories
    
    # Create cron backup
    if crontab -l > /dev/null 2>&1; then
        log_info "Backing up existing crontab..."
        crontab -l > "${PROJECT_DIR}/.pids/crontab_backup_$(date +%Y%m%d_%H%M%S)"
    fi
    
    # Install new crontab
    define_cron_jobs | crontab -
    
    log_success "Cron jobs installed successfully"
    
    # Verify installation
    log_info "Installed crontab:"
    echo "---"
    crontab -l
    echo "---"
}

remove_cron() {
    log_warning "Removing all InkPath cron jobs..."
    
    # Create backup before removal
    if crontab -l > /dev/null 2>&1; then
        crontab -l > "${PROJECT_DIR}/.pids/crontab_backup_$(date +%Y%m%d_%H%M%S)"
        log_info "Crontab backed up to .pids directory"
    fi
    
    # Remove InkPath-specific entries
    crontab -l | grep -v "InkPath" | grep -v "# InkPath" | grep -v "^$" | crontab -
    
    log_success "InkPath cron jobs removed"
}

list_cron() {
    echo "Current crontab:"
    echo "---"
    if crontab -l 2>/dev/null; then
        echo ""
    else
        echo "No crontab installed"
    fi
    echo "---"
    
    echo ""
    echo "Cron job files in project:"
    ls -la "${PROJECT_DIR}/.pids/" 2>/dev/null || echo "No .pids directory"
}

test_cron() {
    log_info "Testing cron job execution..."
    
    echo ""
    echo "=== Testing Agent Run ==="
    cd "${PROJECT_DIR}"
    python -c "
import sys
sys.path.insert(0, '${PROJECT_DIR}')
try:
    from src.services.story_continuation_agent import main
    print('Story continuation agent imported successfully')
    # Uncomment to actually run:
    # main()
except ImportError as e:
    print(f'Import error (expected if agent not implemented): {e}')
except Exception as e:
    print(f'Error: {e}')
"
    
    echo ""
    echo "=== Testing Cron Service ==="
    cd "${PROJECT_DIR}"
    python -c "
import sys
sys.path.insert(0, '${PROJECT_DIR}')
try:
    from src.services.cron_service import check_bot_timeouts
    from src.database import get_db
    db = next(get_db())
    result = check_bot_timeouts(db)
    print(f'Bot timeout check result: {result}')
except Exception as e:
    print(f'Cron service test: {e}')
"
    
    echo ""
    log_success "Cron test completed"
}

show_logs() {
    echo "=== Recent Agent Run Logs ==="
    if [ -f "${AGENT_RUN_LOG}" ]; then
        tail -50 "${AGENT_RUN_LOG}"
    else
        echo "Log file not found: ${AGENT_RUN_LOG}"
    fi
    
    echo ""
    echo "=== Recent Cron Logs ==="
    if [ -f "${CRON_LOG}" ]; then
        tail -30 "${CRON_LOG}"
    else
        echo "Log file not found: ${CRON_LOG}"
    fi
}

enable_cron_service() {
    log_info "Enabling cron service..."
    
    # Ensure cron is running
    if command -v cron &> /dev/null; then
        if command -v systemctl &> /dev/null; then
            sudo systemctl enable cron
            sudo systemctl start cron
            log_success "Cron service enabled via systemctl"
        else
            log_info "Cron service status: $(which cron)"
        fi
    else
        log_warning "Cron not found. Install with: brew install cron"
    fi
}

#===============================================================================
# Main Execution
#===============================================================================

show_help() {
    cat << EOF
InkPath Cron Setup Script

Usage: $0 [OPTIONS]

Options:
    --install     Install cron jobs (default action)
    --remove      Remove all InkPath cron jobs
    --list        List current cron jobs
    --test        Test cron job execution
    --logs        Show recent logs
    --enable      Enable cron service
    --help        Show this help message

Examples:
    $0 --install          Install cron jobs
    $0 --remove            Remove cron jobs
    $0 --test              Test cron job execution
    $0 --logs              View recent logs

Cron Jobs Installed:
    - Story continuation: Every 15 minutes
    - Bot timeout check: Every 5 minutes
    - Activity score update: Hourly
    - Data cleanup: Daily at 3 AM
    - Health check: Every minute

Logs:
    - Agent runs: ${AGENT_RUN_LOG}
    - Cron jobs: ${CRON_LOG}
EOF
}

# Parse arguments
case "${1:-}" in
    --install)
        install_cron
        ;;
    --remove)
        remove_cron
        ;;
    --list)
        list_cron
        ;;
    --test)
        test_cron
        ;;
    --logs)
        show_logs
        ;;
    --enable)
        enable_cron_service
        ;;
    --help|-h)
        show_help
        ;;
    "")
        install_cron
        ;;
    *)
        log_error "Unknown option: $1"
        show_help
        exit 1
        ;;
esac
